# Общие настройки
line-length = 100
target-version = "py311"

# Настройки линтинга
[lint]
select = ["ALL"]
ignore = ["PERF203", # Использование `try`-`except` внутри цикла снижает производительность
          "BLE001", # Не перехватывайте все исключения слепо: `Exception`
          "PD010", # Используйте pivot_table вместо pivot
          "PD009",  # Используйте `.iloc` вместо `.iat`. Если важна скорость, используйте NumPy.
          "PD008",  # Используйте `.loc` вместо of `.at`. Если важна скорость, используйте NumPy.
          "T201", # print
          "D203",
          "D213",
          "COM812",
          "PTH123", "PTH120","PTH118", "PTH110", "PTH107", "PTH207", "PTH103", "PTH100", # путь Path вместо os
          "RUF001", "RUF002", "RUF003",   # Кириллица
          "E501",     # Слишком длинные строки (может включать кириллический текст)
]

[format]
quote-style = "double" # Использовать двойные кавычки для строк
indent-style = "space" # Использовать пробелы для отступов
skip-magic-trailing-comma = false # Пропускать ли добавление завершающих запятых для однострочных коллекций
docstring-code-format = true # Форматировать блоки кода в строках документации
preview = true # Включить экспериментальные функции форматирования (используйте с осторожностью)